### ISSUE TITLE
Full screen photo view

### ISSUE THREAD

**Issue by HirIMogul** [surcoufx83/php-recipe-collection#128]
The current implementation of the image view is suboptimal because it does not utilize the whole screen. This is especially relevant for mobile devices with small screens. 

Suggestion for improvement: Implement the PhotoSwipe library in 'minimal mode': https://photoswipe.com/ to improve screen utilization and user feedback when interacting with the image (tap, zoom, swipe).

**Comment by surcoufx83** [comment]
PhotoSwipe is added and available for testing
9d4ce606858ee5cd3cef9941fad2f6b3ce0faf06
